# Check for ZLIB
FIND_PACKAGE(ZLIB)
IF (ZLIB_FOUND)
    MESSAGE("ZLIB lib: ${ZLIB_LIBRARY}")
    MESSAGE("ZLIB include: ${ZLIB_INCLUDE_DIR}")
ELSE (ZLIB_FOUND)
    MESSAGE(FATAL_ERROR "ZLIB not found. Please install zlib to continue.")
ENDIF(ZLIB_FOUND)

# Check Perl minimum version
FUNCTION(PERL_REQ_VER VER)
    FIND_PACKAGE(Perl)
    IF (PERL_FOUND)
        IF (PERL_VERSION_STRING VERSION_GREATER ${VER} OR PERL_VERSION_STRING VERSION_EQUAL ${VER})
            MESSAGE(STATUS "Perl >= ${VER} (${PERL_VERSION_STRING})")
        ELSE ()
            MESSAGE(FATAL_ERROR "Error: Perl version must be >= ${VER}. You have ${PERL_VERSION_STRING}.")
        ENDIF ()
    ELSE (PERL_FOUND)
        MESSAGE(FATAL_ERROR "Error: ${PACKAGE_NAME} requires Perl version ${VER} in order to run.")
    ENDIF(PERL_FOUND)
ENDFUNCTION(PERL_REQ_VER)

# Check GCC minimum version
FUNCTION(GCC_REQ_VER VER)
    MESSAGE(STATUS "Checking GCC version...")
    EXECUTE_PROCESS(COMMAND ${CMAKE_C_COMPILER} -dumpversion
        OUTPUT_VARIABLE GCC_VERSION)
    STRING(REGEX REPLACE "(\r?\n)+$" "" GCC_VERSION "${GCC_VERSION}")

    IF(GCC_VERSION VERSION_GREATER ${VER} OR GCC_VERSION VERSION_EQUAL ${VER})
        MESSAGE(STATUS "GCC version >= ${VER} (${GCC_VERSION})")
    ELSE()
        MESSAGE(FATAL_ERROR "Error: GCC version must be >= ${VER}. You have ${GCC_VERSION}")
    ENDIF()
ENDFUNCTION(GCC_REQ_VER)

# Check GLIBC minimum version
FUNCTION(GLIBC_REQ_VER VER)
    MESSAGE(STATUS "Checking GLIBC version...")
    EXECUTE_PROCESS(COMMAND /lib/libc.so.6
        OUTPUT_VARIABLE GLIBC_VERSION)
    STRING(REGEX MATCH "[0-9]\\.[0-9][0-9]?" GLIBC_VERSION "${GLIBC_VERSION}")
    MESSAGE(STATUS "GLIBC version: ${GLIBC_VERSION}")

    IF(GLIBC_VERSION VERSION_LESS ${VER} OR GLIBC_VERSION VERSION_EQUAL ${VER})
        MESSAGE(STATUS "Downloading legacy build of TRF...")
        SET(TRFDLName "trf${TRFVer}.legacy${ARCH}" PARENT_SCOPE)
    ENDIF()
ENDFUNCTION(GLIBC_REQ_VER)

# Check for samtools
FUNCTION(SAMTOOLS_REQ_VER VER)
    MESSAGE(STATUS "Checking samtools version...")
    EXECUTE_PROCESS(COMMAND samtools --version | head -1
        OUTPUT_VARIABLE SAMTOOLS_VERSION)
    STRING(REGEX MATCH "[0-9]\\.[0-9][0-9]?" SAMTOOLS_VERSION "${SAMTOOLS_VERSION}")

    IF(SAMTOOLS_VERSION VERSION_GREATER ${VER} OR SAMTOOLS_VERSION VERSION_EQUAL ${VER})
        MESSAGE(STATUS "samtools version >= ${VER} (${SAMTOOLS_VERSION})")
    ELSE()
        MESSAGE(FATAL_ERROR "Error: samtools version must be >= ${VER}. You have ${SAMTOOLS_VERSION}")
    ENDIF()
ENDFUNCTION(SAMTOOLS_REQ_VER)

# Check for bedtools
FUNCTION(BEDTOOLS_REQ_VER VER)
    MESSAGE(STATUS "Checking bedtools version...")
    EXECUTE_PROCESS(COMMAND bedtools --version | head -1
        OUTPUT_VARIABLE BEDTOOLS_VERSION)
    STRING(REGEX MATCH "[0-9]\\.[0-9][0-9]?\\.[0-9]" BEDTOOLS_VERSION "${BEDTOOLS_VERSION}")

    IF(BEDTOOLS_VERSION VERSION_GREATER ${VER} OR BEDTOOLS_VERSION VERSION_EQUAL ${VER})
        MESSAGE(STATUS "bedtools version >= ${VER} (${BEDTOOLS_VERSION})")
    ELSE()
        MESSAGE(FATAL_ERROR "Error: bedtools version must be >= ${VER}. You have ${BEDTOOLS_VERSION}")
    ENDIF()
ENDFUNCTION(BEDTOOLS_REQ_VER)
